#!/bin/bash

if [[ "1" > "2" ]] then
  echo "1) error!!"
  exit 1
else
  echo "1) 2 is bigger the 1"
  if [[ -n "2" ]] then
    echo "Input: [yes/no]"
  fi
fi

read confirmation
case $confirmation in
  yes)
    echo "Hello, case-in operator!"
    ;;
  no)
    echo "Skip code block"
    ;;
  *)
    echo "Wrong input!"
esac
