#!/bin/bash

echo "Running echo script..."
./echo

echo "Running equalif script..."
./equalif -a -a

echo "Different parameters"
./equalif -a -b

echo "Running equalsif script..."
./equalsif -a -a -a

echo "Dirrefent parameters"
./equalsif -a -b -c

echo "Conditions and boolean operators"
./csbo

echo "For-in elements"
./loops

echo "While condition"
./while_loops

echo "Math results:"
./math 2 + 2
./math 5 - 1
./math 2 \* 2
./math 8 / 2
