#!/bin/bash

confimation=no
while [ "$confimation" = "no" ]
do
  echo "Confirm? [yes/no]"
  read confirmation
  echo "Your input: $confirmation"
  if [[ "$confirmation" == "yes" ]] then
    exit 0
  fi
done
