#!/bin/bash

if [ -z $1 ]; then
  read -p "Input compiler [gcc/clang]: " compiler
else
  compiler=$1
fi

case $compiler in
gcc)
  echo "Compile with gcc compiler"
  gcc main.c -O3 -o main.out
  ;;
clang)
  echo "Compile with clang compiler"
  clang main.c -O3 -o main.out
  ;;
*)
  echo "Compiler not found!"
  exit 404
  ;;
esac
